/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ryan_test.test_language_tags.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ShowPetByIdResponse {
    
    public String contentType;

    public ShowPetByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * unexpected error
     */
    
    public ryan_test.test_language_tags.models.shared.Error error;

    public ShowPetByIdResponse withError(ryan_test.test_language_tags.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * Expected response to a valid request
     */
    
    public ryan_test.test_language_tags.models.shared.Pet pet;

    public ShowPetByIdResponse withPet(ryan_test.test_language_tags.models.shared.Pet pet) {
        this.pet = pet;
        return this;
    }
    
    
    public Integer statusCode;

    public ShowPetByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ShowPetByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ShowPetByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
