/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ryan_test.test_language_tags;

import ryan_test.test_language_tags.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "0.1.0";
	public String genVersion = "2.84.3";
	
}